### ISSUE TITLE
Doesn't work for Safari Version 16.6 (18615.3.12.11.2)

### ISSUE THREAD

**Issue by spookMaster** [GoogleChromeLabs/link-to-text-fragment#91] opened 2023-07-31 08:56 UTC
Extension installs. Can be enabled and set for ALL websites. Context menu item appears, but when clicked does not change the contents of the clipboard.

**Comment by tomayac** [comment] 2023-07-31 09:32
Duplicate of https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/69.

**Closed by tomayac** 2023-07-31 09:32 UTC
