### ISSUE TITLE
Does not work on Firefox anymore

### ISSUE THREAD

**Issue by Qhilm** [GoogleChromeLabs/link-to-text-fragment#95] opened 2023-09-14 06:53 UTC
Currently, the only way to get it to work on Firefox is:
1. load the link to text fragment
2. it fails
3. click on the "link to text fragment" add-on icon
4. Error is displayed "INVALID_SELECTION: The selection provided could not be used."
5. reload web page in Firefox
6. it works, text fragment is highlighted.

These steps must be repeated for every link, hence it's not very usable anymore.

Example link: https://blog.chromium.org/2019/12/chrome-80-content-indexing-es-modules.html#:~:text=ECMAScript%20Modules%20in%20Web%20Workers

Firefox 117.0.1
macOS 13.5.2

**Comment by tomayac** [comment] 2023-09-14 08:06
I'm not sure what changed on the Firefox side. It was working just fine, but I can confirm that it stopped working on Firefox 117 now. It uses manifest v3, so maybe there's some problem there? You can see the [recent commits](https://github.com/GoogleChromeLabs/link-to-text-fragment/commits/main/) if you want to investigate. 

There's a known issue on Chrome (and probably Firefox), where extension contexts can't use the Async Clipboard API because it's not focused. In Chrome, this is tracked as https://crbug.com/1404835.

**Comment by rokejulianlockhart** [comment] 2023-09-19 18:06
https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/42837531/a790f05a-b275-47cc-88ce-e8eec0f5a8f7

![Screenshot_20230919_185952](https://github.com/GoogleChromeLabs/link-to-text-fragment/assets/42837531/75422e44-1ecc-43c8-99ea-05efa7019483)

**Comment by johnmaguire** [comment] 2023-11-03 14:55
Firefox 119 on macOS Sonoma. I no longer see the "Copy link to selected text" context menu item.

**Comment by Qhilm** [comment] 2023-11-03 14:58
> Firefox 119 on macOS Sonoma. I no longer see the "Copy link to selected text" context menu item.

you may have to click on the add-on icon once.

**Comment by budak7273** [comment] 2024-01-27 20:22
Seems to be working without any additional steps for me on Windows firefox 121.0.1 (64-bit)

**Comment by krystian3w** [comment] 2024-08-28 21:38
Should works without add-ons at Firefox Nightly 131.

**Comment by Pfeil** [comment] 2024-10-18 12:09
MacOS Sonoma 14.7
Firefox 131.0.3

- Today, I first made a successful link and sent it to someone.
- I wanted to create a second one on the same site, the URL still being a text fragment link created before.
- Resulted in the clipboard still containing the old content, no error message as far as I can tell.
- Removed the text fragment part in the URL, still doesn't work (nothing happens).
- Then, I also had the issue of the link disappearing, clicked the icon once to make it appear again. Icon reappeared, but still doesn't work.
- Reinstalled the extension and restarted Firefox, still does not work. Just nothing happens, on several pages I tried.

**Comment by tomayac** [comment] 2024-10-18 12:31
@dotproto Could the above https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/95#issuecomment-2422326148 be related to the trick you mentioned in https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/108#issuecomment-2414185289? Is it a full replacement of the service worker?

**Comment by tomayac** [comment] 2024-10-19 16:25
Alright, rolled back to `v2.3.2`. @dotproto, the trick from https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/108#issuecomment-2414185289 unfortunately doesn't seem like a drop-in replacement after all. The validation when uploading the new version could have caught this: https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/84c592c3754ff3259cc4e473865dbd8a8def2396/service_worker.js#L29

**Comment by Pfeil** [comment] 2024-10-25 21:30
I successfully copied a link yesterday, same machine. Didn't look at the version, I just gave it a shot and was happy it worked. So I assume the rollback has worked. Thanks!

**Comment by tomayac** [comment] 2024-10-28 09:16
Thanks for confirming! We're in a funny world right now where Firefox continues manifest v2 support and has partial manifest v3 support, and where Chrome phases out manifest v2 support and forces a manifest v3 migration, which it fully supports, but which lacks rich clipboard support in service worker offscreen documents (https://crbug.com/1404835). This is not a problem on Firefox, though, as we can remain on the manifest v2 version, so closing this Issue.

**Closed by tomayac** 2024-10-28 09:16 UTC
